---
- name: Remove Jenkins Servers
  hosts: all
  gather_facts: false
  connection: local
  become: false
  vars:
    provider: vmware
  vars_files:
    - node-config/nodes-{{ provider }}.yml

  roles:
    - role: ansible-role-{{ provider_role | default(provider) }}
      role_action: deprovision
      delegate_to: localhost
      run_once: true
