- hosts: localhost
  become: false
  tasks:
    - name: get ec2 instance information
      amazon.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ ec2_vpc_id }}"
          "tag:app": jenkins_tower_demo
      register: ec2_instances

    - name: create DNS entry if it doesn't exist
      community.aws.route53:
        state: present
        overwrite: yes
        zone: "{{ hosted_zone_domain_name }}"
        record: "{{ subdomain | default(ec2_instances.instances[0].tags.role | lower) }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        type: A
        value: "{{ ec2_instances.instances[0].public_ip_address }}"
        wait: true
      when:
        - ec2_instances.instances is defined
        - ec2_instances.instances | length > 0
        - ec2_instances.instances[0].public_ip_address

    - name: output url
      debug:
        msg: 'application is available at http://{{ subdomain | default(ec2_instances.instances[0].tags.role | lower) }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}/'