- hosts: all
  become: true
  vars:
    jenkins_admin_username: admin
    jenkins_admin_password: 'admin'
    jenkins2_cli_username: "{{ jenkins_admin_username }}"
    jenkins2_cli_password: "{{ jenkins_admin_password }}"
    jenkins2_config_http_port: 8080
    jenkins2_credentials_enabled: True
    jenkins2_credentials:
      githubtoken:
        type: 'secrettext'
        id: 'github_token'
        description: 'github credentials'
        token: "{{ github_token | default('') }}"
    jenkins2_github_enabled: True
    github_external_url: https://api.github.com
    github_manage_hooks: False
    jenkins2_github_token_cred: github_token
    jenkins_http_port: '{{ jenkins2_config_http_port }}'
    jenkins_plugins:
      - ant
      - antisamy-markup-formatter
      - blueocean
      - configuration-as-code
      - build-timeout
      - cloudbees-folder
      - credentials-binding
      - ec2
      - email-ext
      - file-operations
      - git
      - gitlab-plugin
      - gradle
      - ldap
      - mailer
      - matrix-auth
      - pipeline-stage-view
      - pipeline-utility-steps
      - ssh-agent
      - ssh-slaves
      - timestamper
      - workflow-aggregator
      - ws-cleanup
      - job-dsl
      - checkstyle
      - log-parser
      - pmd
      - warnings-ng
      - permissive-script-security
  tasks:
    - name: import epel gpg key
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
      when: ansible_os_family in ['RedHat', 'Rocky']

    - include_role:
        name: oatakan.rhn
      when:
        - ansible_os_family == 'RedHat'
        - ec2_image_id is undefined

    - include_role:
        name: oatakan.rhel_upgrade
      when: ansible_os_family in ['RedHat', 'Rocky']

    - include_role:
        name: "{{ role_name }}"
      loop_control:
        loop_var: role_name
      loop:
        - geerlingguy.java
        - geerlingguy.jenkins
#        - lean_delivery.jenkins

    - name: pip
      block:
        - name: install pip
          package:
            name: python{{ ansible_facts.python.version.major }}-pip
            state: present
          register: pip_install_status
          until: pip_install_status is succeeded

        - name: upgrade pip
          pip:
            name:
              - pip
            state: present
            extra_args: --upgrade
            executable: 'pip{{ ansible_facts.python.version.major }}'
          register: pip_upgrade
          until: pip_upgrade is success

        - name: install pip packages
          pip:
            name:
              - python-jenkins
              - lxml
            state: present
            executable: 'pip{{ ansible_facts.python.version.major }}'
          register: install_pip_packages
          until: install_pip_packages is success
      become: true
