---
- name: Restart Jenkins if needed
  become: true

  - ansible.builtin.service:
      name: jenkins
      state: restarted
    register: restart_jenkins_handler_in_handler
    ignore_errors: true

  - ansible.builtin.uri:
      url: http://localhost:{{ jenkins2_config_http_port }}/login
      status_code: 200
      timeout: 5
    register: jenkins_service_status_handler_in_handler
    until: jenkins_service_status_handler_in_handler.status == 200
    retries: 60
    delay: 5
