---
- name: Restart Jenkins if needed
  become: true
  block:
    - name: Restart Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: restarted
      register: restart_jenkins_handler # Renamed register to avoid conflict if this handler is called multiple times in a play
      ignore_errors: true

    - name: Wait for Jenkins to start up after restart
      ansible.builtin.uri:
        url: http://localhost:{{ jenkins2_config_http_port }}/login
        status_code: 200
        timeout: 5
      register: jenkins_service_status_handler # Renamed register
      until: jenkins_service_status_handler.status == 200
      retries: 60
      delay: 5
