---

- name: set credentials
  jenkins_script:
    url: "http://localhost:{{ jenkins2_config_http_port }}"
    script: "{{ lookup('template', 'set-credentials.groovy.j2') }}"
    user: '{{ jenkins2_cli_username }}'
    password: '{{ jenkins2_cli_password }}'
    validate_certs: no
    timeout: 120

- name: create tower configuration
  template:
    src: configure_ansible_tower.xml.j2
    dest: "{{ jenkins2_home_directory }}/org.jenkinsci.plugins.ansible_tower.AnsibleTower.xml"
    owner: "{{ jenkins2_user }}"
    group: "{{ jenkins2_user }}"
    mode: 0644
  become: yes

- include_tasks: plugin.yml

- name: create tower job
  jenkins_job:
    config: "{{ lookup('template', 'tower_job.xml.j2') }}"
    name: Ansible Tower Project
    password: "{{ jenkins2_cli_password }}"
    user: "{{ jenkins2_cli_username }}"
    url: "http://localhost:{{ jenkins2_config_http_port }}"

