---
- name: Enable Ansible Tower plugin
  community.general.jenkins_plugin:
    name: ansible-tower
    state: present
    url_username: "{{ jenkins2_cli_username }}"
    url_password: "{{ jenkins2_cli_password }}"
    validate_certs: false
  register: jenkins_tower_plugin
  notify: Restart Jenkins if needed
