---

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
  register: restart_jenkins
  ignore_errors: yes

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:{{ jenkins2_config_http_port }}
    return_content: yes
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  retries: 60
  delay: 5
  until: not jenkins_service_status.failed