---

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
  register: restart_jenkins
  ignore_errors: yes

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:{{ jenkins2_config_http_port }}/login
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  until: jenkins_service_status.status == 200
  retries: 60
  delay: 5