---

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:{{ jenkins2_config_http_port }}
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  retries: 60
  delay: 5
  until:
    - ('status' in jenkins_service_status)
    - jenkins_service_status['status'] == 200

- name: Stop Jenkins first
  command: systemctl stop jenkins
  ignore_errors: yes

#- name: Stop Jenkins first
#  service:
#    name: jenkins
#    state: stopped
#  ignore_errors: yes

- name: Restart Jenkins
  service:
    name: jenkins
    state: started
  register: restart_jenkins
  until: restart_jenkins is success
  delay: 3
  retries: 5
  ignore_errors: yes

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:{{ jenkins2_config_http_port }}
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  retries: 60
  delay: 5
  until:
    - ('status' in jenkins_service_status)
    - jenkins_service_status['status'] == 200